[package]
name = "mkv_to_wav"
author = "Nestor Wheelock"
description = "converts mkv to wav"
license = "GNU GPLv3"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"
filetime = "0.2"
chrono = "0.4"
